In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
path = 'ImageAtten'
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['billgates.jpeg', 'elon musk.jpeg', 'ishant.jpg', 'jack.jpeg', 'Sandhya.jpg']


In [3]:
for cl in myList:
    currImg = cv2.imread(f'{path}/{cl}')
    images.append(currImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['billgates', 'elon musk', 'ishant', 'jack', 'Sandhya']


In [4]:
def findencodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

In [5]:
encodelistKnown = findencodings(images)
print('encoding complete')

encoding complete


In [6]:
def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M')
            f.writelines(f'\n{name},{dtString}')


In [7]:
#initialize webcam
cap = cv2.VideoCapture(0)

In [ ]:
while True:
    success, img = cap.read()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(imgS,cv2.COLOR_BGR2RGB)
    
    facesCurrFrames = face_recognition.face_locations(imgS)
    encodesCurrFrames = face_recognition.face_encodings(imgS,facesCurrFrames)
    
    for encodeface,faceloc in zip(encodesCurrFrames,facesCurrFrames):
        matches = face_recognition.compare_faces(encodelistKnown,encodeface)
        facedis = face_recognition.face_distance(encodelistKnown,encodeface)
        print(facedis)
        matchIndex = np.argmin(facedis)
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceloc
            y1,x2,y2,x1 = y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
    cv2.imshow('Webcam',img)
    cv2.waitKey(1)

[0.81178153 0.82849176 0.45873881 0.73529425 0.69956415]
ISHANT
[0.77384748 0.77863615 0.49755704 0.69222859 0.72096771]
ISHANT
[0.76071439 0.75572312 0.44319898 0.67777844 0.71820742]
ISHANT
[0.76222836 0.74754497 0.4428834  0.78524501 0.76081856]
ISHANT
[0.75110193 0.75835511 0.47606677 0.73230766 0.74657157]
ISHANT
[0.79938514 0.7821474  0.37917422 0.71481484 0.71709307]
ISHANT
[0.77793228 0.7848832  0.45741961 0.67795107 0.70414934]
ISHANT
[0.79454853 0.80976726 0.45074107 0.71051725 0.7377879 ]
ISHANT
[0.80262806 0.8048393  0.44184071 0.71317664 0.75652076]
ISHANT
[0.75067649 0.76846342 0.35908165 0.69382483 0.66702046]
ISHANT
